apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    app: {{.Values.labelvalue}}
  ports:
    - protocol: {{.Values.protocol}}
      port: {{.Values.port}}
      targetPort: {{.Values.targetPort}}
  type: {{.Values.clusterType}}
